# H2 Web Console Dev Profile Configuration
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Admin Master Key for Local Dev Profile
causa.admin.key=changeme-local-dev-key

